### ISSUE TITLE
Problems with new version

### ISSUE THREAD

**Issue by Victor-Munoz-Albornoz** [afedynitch/MCEq#11]
Hi, 

I have just installed the latest version of the software on a Windows machine with no troubles.

However, when running the _Partial_hadron_contributions.ipynb_ notebook I get the error message:
"No module named 'CRFluxModels"

Then I go to see what was actually installed and I noticed that also didn't have anything in the MCEq.data  folder.

In previous versions, in addition to having the CRFluxModels module,  I used to have several data in the MCEq.data  folder like HadAirCrossSections, InteractionYields, etc. 

What should I do to solve all of this at the latest version?

Cheers,
Víctor

**Comment by afedynitch** [comment]
Hi Victor,

the data folder is empty if you check out the code. If you use pip to install it, then usually the MCEq folder will be somewhere in your site-packages and managed by pip. When you import mceq_config for the first time, or any other MCEq module, then the data file will be downloaded automatically. The new version stores everything in a single database file in HDF5 format.

Regarding the aforementioned partial-hadron-... example. It is currently not working and will come back somewhat later. If you really need this, use the classic repository.

Cheers,
Anatoli

**Comment by Victor-Munoz-Albornoz** [comment]
Thanks, problem solved!
