### ISSUE TITLE
New location request for atmospheric models

### ISSUE THREAD

**Issue by Kakiczi** [afedynitch/MCEq#12]
Hi,

I would like to request an extra location: ANTARES/KM3NeT-ORCA

The parameters are:
ATMOD 0
ATMLAY 750000.000000000        1050000.00000000   3850000.00000000        10500000.0000000
ATMA  -160.619353520869       -94.1988571812849       0.811592824013076 -6.995682173567275E-004
ATMB  1198.61935352087        1151.42815828301        1319.63474626067   449.651355809074
ATMC  977647.643069855        878153.550000000        636143.040000000 811710.055731307

**Comment by afedynitch** [comment]
Hi!

OK, no problem I'll include it in the next minor update at the end of this week.
Thanks for the suggestion.

**Comment by afedynitch** [comment]
What should I put as a reference for these parameters? Any kind of source such as paper/arxiv/thesis/wiki/email is okay. Just that the users who may encounter it know where these values come from.

**Comment by Kakiczi** [comment]
[Thomas_Heid_PhD_thesis.pdf](https://github.com/afedynitch/MCEq/files/4280984/Thomas_Heid_PhD_thesis.pdf)

I would put this thesis by T. Heid. Not sure if it's published anywhere.

Here you actually even have more values (separately for ORCA and ARCA sites and separately for summer and winter) on pages 106,107. ORCA and ANTARES are pretty much at the same location, so you could just do ORCA/ANTARES and ARCA.

**Comment by afedynitch** [comment]
This is now implemented in version 1.1.1. Update using:

     pip install MCEq --upgrade

**Comment by Kakiczi** [comment]
Great, thanks!
