### ISSUE TITLE
Add ARCA location and seasonal variants for KM3NeT atmosphere

### ISSUE THREAD

**Issue by Kakiczi** [afedynitch/MCEq#14]
Hi, it's me again. Could you please also include ARCA atmosphere and both summer and winter options, as in the thesis by T. Heid? I want to do a systematics study with MCEq, so this is quite crucial for me.

It is:

**Parameters for the ARCA-Summer:**
Layer: 1 2 3 4 5
ATMA -157.857 -28.7524 0.790275 -0.0286999 0.481114
ATMB 1190.44 1171.0 1344.78 445.357
ATMC 1006100.0 758614.0 636790.0 817384.0 16886800.0
ATMLAY 9.0e5 18.0e5 38.0e5 68.2e5

**Parameters for the ARCA-Winter:**
Layer: 1 2 3 4 5
ATMA -116.391 3.5938 0.474803 -0.0246031 0.280225
ATMB 1155.63 1501.57 1271.31 398.512
ATMC 933697.0 594398.0 636790.0 810924.0 29618400.0
ATMLAY 12.25e5 21.25e5 43.0e5 70.5e5

**Parameters for ORCA-Summer:**
Layer: 1 2 3 4 5
ATMA -158.85 -5.38682 0.889893 -0.0286665 0.50035
ATMB 1145.62 1176.79 1248.92 415.543
ATMC 998469.0 677398.0 636790.0 823489.0 16090500.0
ATMLAY 9.0e5 22.0e5 38.0e5 68.2e5

**Parameters for ORCA-Winter:**
Layer: 1 2 3 4 5
ATMA -132.16 -2.4787 0.298031 -0.0220264 0.348021
ATMB 1120.45 1203.97 1163.28 360.027
ATMC 933697.0 643957.0 636790.0 804486.0 23109000.0
ATMLAY 9.5e5 22.0e5 47.0e5 68.2e5

**Comment by afedynitch** [comment]
Hi!

No problem, I can add these. Unfortunately I'm quite busy until the end of this week.
It may accelerate progress if you can have a look at density_profiles.py, where all the
atmospheres are defined in the simple if-elseif statements. If you can bring the
numbers you pasted in the required shape and re-paste them here, I can finish the rest.
The _thickl variables can be computed by initializing the atmosphere object and calling
calc_thickl(). But I can do the last step if this is too finicky.

Alternatively, feel free to fork and submit a pull request if you know how it works.

**Comment by Kakiczi** [comment]
Ok, I just did a pull request, so this issue can be closed.
