### ISSUE TITLE
Add support to release linux aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [afedynitch/MCEq#34]
Problem
---------
On aarch64, `pip install mceq` build the wheels from source code and then installs it. It requires the user to have a development environment installed on their system. Also, it takes more time to build the wheels than downloading and extracting the wheels from PyPI.

Resolution
-----------
On aarch64, `pip install mceq` should download the wheels from PyPI.

@afedynitch, Please let me know your interest in releasing aarch64 wheels. I can help with this.

**Comment by afedynitch** [comment]
Hi!

Thanks for submitting this issue and the news that it works on aarch64. Do you mean aarch64 on Mac OS?
This is definitely very high on my priority list, just waiting for my new laptop that should arrive within the next few days/week.

If it's aarch64 on linux then your help with that would be appreciated. In this case, please follow the commands in the azure pipeline (the .ci folder) to build and share the wheel.

**Comment by afedynitch** [comment]
Closed by PR #35 

Cheers.
