### ISSUE TITLE
Array size mismatch in numpy kernel

### ISSUE THREAD

**Issue by austinschneider** [afedynitch/MCEq#6]
When calling `MCEqRun.solve` with `kernel_config=='numpy'`

> Traceback (most recent call last):
>   File "main.py", line ..., in <module>
>     mceq_run.solve()
>   File "./MCEq/core.py", line 1123, in solve
>     self._forward_euler(**kwargs)
>   File "./MCEq/core.py", line 1307, in _forward_euler
>     self.solution, self.grid_sol = kernel(*args)
>   File "./MCEq/kernels.py", line 132, in kern_numpy
>     mu_egrid, mu_egrid + mu_dEdX * dXaccum,
> ValueError: operands could not be broadcast together with shapes (88,) (89,)

**Comment by afedynitch** [comment]
Hi Austin,
sorry for silence. This issue had to do with the present version and disappears for different reasons in the release version that I'm working on.

Thanks for pointing this out.
