### ISSUE TITLE
Resonance to Hadron transition

### ISSUE THREAD

**Issue by PilarHG** [afedynitch/MCEq#9]
Hello, I have noticed an typo in the documentation (I think), the previous to last object cs_db in 
class MCEq.data.MCEqParticle() should be HadAirCrossSections and not InteranctionYields. 

Besides I am trying to extract some info on the threshold for resonance-> hadron transition for D mesons and it does not seem to work. For D+ mesons, E_mix returns 0 and residx (0,0), while the flux of D+ mesons obtained with get_solution is exactly zero below some energy in the energy grid, so I 
assume it is indeed doing the hybrid treatment.

I am not sure what I am doing wrong...

Is there a way to extract the D meson flux below the critical energy ?

Thanks, Pilar

**Comment by afedynitch** [comment]
These issue was relevant for the obsolete MCEq_classic repo but is not applicable to the post v1.xx versions.
